name: 'Perform deployment on the application'
description: '..'
inputs:
  application:
    description: '...'
    required: true
runs:
  using: "composite"
  steps:
    - name: Rolling update for frontend
      shell: bash
      run: |
        kubectl set image deployment/webapp-${{ inputs.application }}-new webapp-${{ inputs.application }}-new=mtararujs/${{ inputs.application }}:$GITHUB_SHA