apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-deployment-new
  labels:
    app: postgres-db-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db-new
  template:
    metadata:
      labels:
        app: postgres-db-new
    spec:
      containers:
      - name: postgres-db-new
        image: mtararujs/postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            value: mysecretpassword
          - name: POSTGRES_DB
            value: mydatabase
