apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-backend-new
  labels:
    app: backend-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-new
  template:
    metadata:
      labels:
        app: backend-new
    spec:
      containers:
      - name: webapp-backend-new
        image: mtararujs/webapp-backend:latest
        ports:
          - containerPort: 5050

