apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service-new
spec:
  selector:
    app: webapp-frontend-new
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer