# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
      - name: Build Webapp Frontend application
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/build
        with:
          application: frontend
          docker_image_tag: ${{ secrets.DOCKER_USERNAME }}/frontend:$GITHUB_SHA
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Build Webapp Backend application
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/build
        with:
          application: backend
          docker_image_tag: ${{ secrets.DOCKER_USERNAME }}/backend:$GITHUB_SHA
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-production:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
      - name: Deploy Frontend application to PROD
        if: steps.filter.outputs.frontend == 'true'
        uses: ./.github/actions/deploy
        with:
          application: frontend
      - name: Deploy Backend application to PROD
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/deploy
        with:
          application: backend

  api-test-production:
    name: Run API Tests against PROD
    runs-on: self-hosted
    needs: [deploy-production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Run API tests
        if: steps.filter.outputs.backend == 'true'
        uses: ./.github/actions/test
        with:
          test_env: PRD