# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Build Webapp Frontend application
        uses: ./.github/actions/build
        with:
          application: frontend
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Build Webapp Backend application
        uses: ./.github/actions/build
        with:
          application: backend
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy-production:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    if: success()

    steps:
      - name: Deploy Frontend application
        uses: ./.github/actions/deploy
        with:
          application: frontend
      - name: Deploy Backend application
        uses: ./.github/actions/deploy
        with:
          application: backend

  api-test-production:
    name: Run Tests
    runs-on: self-hosted
    needs: [deploy-production]
    steps:
      - name: Run API tests
        uses: ./.github/actions/test
        with:
          test_env: PRD